using UnityEngine;
using UnityEngine.Rendering;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
namespace Skybreak {
public enum FlightState { Hangar, Briefing, Playing, Paused, Upgrade, Victory, Defeat }
public class Hostile {
 public Hostile owner;public Vector3 mountOffset;public int bossAttackIndex;public float attackClock,coreExpose;public bool aimReady;public Vector3 lockedAim;public LineRenderer aimLine;
 public GameObject go;public Vector3 pos,origin;public int kind,pattern;public float hp,maxHp,age,fire,phase,flash,recoil;public Color[] baseColors;public bool boss,elite;public Renderer[] renderers;
}
public struct Round {public Vector3 pos,prev,velocity;public float life,radius,damage,curve;public int style,pierce,kind;public float age;public Hostile lastHit;public bool friendly,grazed,homing;}
public struct Spark {public Vector3 pos,velocity;public float life,max,size;public int style;}
public class Supply {public GameObject go;public Vector3 pos;public int kind;public float age;}
public class Beam {public float x,age,duration;public GameObject go;public LineRenderer line;public bool fired;}
public partial class SkyGame:MonoBehaviour {
 public static SkyGame Instance;
 public FlightState State=FlightState.Hangar;public int Stage,Ship,Difficulty,Weapon,Hull,Bombs,Score,HighScore,Combo,MaxCombo,Grazes,Kills,Unlocked;public float Energy,Overdrive,StageTime,CampaignTime,DamageBoost=1;
 public bool AutoFire=true,MouseControl=false,ShakeEnabled=true,MusicEnabled=true;public float MasterVolume=.65f;public bool Endless;public int EndlessLoop;public bool Practice;public int PracticeStage;
 public readonly List<Hostile> Enemies=new List<Hostile>();public readonly List<Round> Bullets=new List<Round>();public readonly List<Supply> Supplies=new List<Supply>();public readonly List<Beam> Beams=new List<Beam>();
 readonly List<Spark> sparks=new List<Spark>();
 readonly List<Matrix4x4> enemyRims=new List<Matrix4x4>(1500);Material projectileRim;
 readonly Dictionary<Hostile,float> pendingDamage=new Dictionary<Hostile,float>();
 public Camera Cam;public SkyWorld World;public GameObject Player;public Vector3 PlayerPos;[NonSerialized] public Hostile Boss;public SkyPost Post;
 GameObject showcase;Transform hitPoint;LineRenderer focusRing;AudioSource music,sfx,gunAudio;Mesh sphere,cube,quad;Material[] shotMats;readonly Matrix4x4[] matrices=new Matrix4x4[1023];readonly List<Matrix4x4>[] draws=new List<Matrix4x4>[8];MaterialPropertyBlock block;
 bool qaRunning;long enemyRoundsSpawned;float fireClock,missileClock,invuln,comboClock,shake,bombFlash,spawnClock,briefClock,warningClock,dialogClock,stageEndClock,stageBanner,hitStop;int waveIndex,bossPhase=-1,upgradeArmor,upgradeFire,upgradeEnergy,stageDamage,campaignDamage;bool bossSpawned;Vector3 cameraBase;Vector2 moveLast;float smoothedFps;public string RadioName="",RadioText="";public int UpgradePick=-1;
 public string[] ShipNames={"苍隼","蝠鲼","银针"};public string[] ShipCodes={"F–07  KESTREL","B–12  MANTA","X–03  NEEDLE"};public string[] StageNames={"曙光海岸","风暴之城","寂静天环"};public string[] StageEnglish={"THE LAST COAST","CITY IN THE STORM","HEART OF THE ARRAY"};public string[] BossNames={"利维坦 · 海上要塞","暴风眼 · 制空平台","炽天使 · 天环核心"};
 public int MaxHull=> (Difficulty==0?6:Difficulty==1?4:3)+upgradeArmor+(Ship==1?1:0)+(PilotLevel(Ship)>=6?1:0)+researchArmor;
 public float DifficultySpeed=>(Difficulty==0?.72f:Difficulty==1?1:1.2f)+EndlessLoop*.06f;
 public float Progress=>Boss!=null?Mathf.Lerp(.83f,1,1-Boss.hp/Boss.maxHp):Mathf.Min(.83f,StageTime/115*.83f);
 void Awake(){Instance=this;Application.targetFrameRate=120;QualitySettings.vSyncCount=1;Time.timeScale=1;LoadSettings();LoadPilotProgress();}
 void Start(){Cam=Camera.main;if(!Cam){Cam=new GameObject("Flight camera").AddComponent<Camera>();Cam.tag="MainCamera";}Cam.orthographic=true;Cam.clearFlags=CameraClearFlags.SolidColor;Cam.orthographicSize=12.8f;Cam.nearClipPlane=.1f;Cam.farClipPlane=350;Cam.allowHDR=true;Cam.allowMSAA=true;cameraBase=new Vector3(0,34,-19);Cam.transform.position=cameraBase;Cam.transform.rotation=Quaternion.Euler(60,0,0);if(!Cam.GetComponent<AudioListener>())Cam.gameObject.AddComponent<AudioListener>();Post=Cam.gameObject.AddComponent<SkyPost>();
 World=new GameObject("Moving world").AddComponent<SkyWorld>();World.Build(Cam);var o=GameObject.CreatePrimitive(PrimitiveType.Sphere);sphere=o.GetComponent<MeshFilter>().sharedMesh;Destroy(o);o=GameObject.CreatePrimitive(PrimitiveType.Cube);cube=o.GetComponent<MeshFilter>().sharedMesh;Destroy(o);o=GameObject.CreatePrimitive(PrimitiveType.Quad);quad=o.GetComponent<MeshFilter>().sharedMesh;Destroy(o);
 shotMats=new[]{Art.Mat("pulse",Art.Cyan,true),Art.Mat("danger",Art.Orange,true),Art.Mat("violetbullet",Art.Violet,true),Art.Mat("hot core",new Color(1,.86f,.52f),true),Art.Mat("smoke",new Color(.055f,.07f,.09f)),Art.Mat("debris",new Color(.27f,.32f,.36f)),Art.Mat("repair",new Color(.13f,1,.55f),true),Art.Mat("missile",new Color(.3f,.7f,1),true)};for(int i=0;i<8;i++){draws[i]=new List<Matrix4x4>(1500);if(i!=4&&i!=5){var mat=new Material(Shader.Find("Skybreak/Projectile"));mat.color=shotMats[i].color;mat.enableInstancing=true;shotMats[i]=mat;}}shotMats[4]=new Material(Shader.Find("Skybreak/Smoke"));shotMats[4].enableInstancing=true;block=new MaterialPropertyBlock();projectileRim=new Material(Shader.Find("Skybreak/ProjectileRim"));projectileRim.enableInstancing=true;
 music=gameObject.AddComponent<AudioSource>();music.loop=true;music.spatialBlend=0;sfx=gameObject.AddComponent<AudioSource>();sfx.spatialBlend=0;gunAudio=gameObject.AddComponent<AudioSource>();gunAudio.spatialBlend=0;SetupFeedback();ChangeMusic(3);SetupHangar();
#if !UNITY_WEBGL || UNITY_EDITOR
 string[] args=Environment.GetCommandLineArgs();if(Array.IndexOf(args,"--sky-test")>=0)StartCoroutine(VerifyRuntime());else if(Array.IndexOf(args,"--sky-campaign-test")>=0)StartCoroutine(VerifyCampaign());else if(Array.IndexOf(args,"--sky-portrait-preview")>=0)StartCoroutine(CapturePortraitMotion());
#endif
 }
 public void LoadSettings(){HighScore=PlayerPrefs.GetInt("highscore",0);Unlocked=PlayerPrefs.GetInt("unlocked",0);Ship=Mathf.Clamp(PlayerPrefs.GetInt("ship",0),0,2);Difficulty=Mathf.Clamp(PlayerPrefs.GetInt("difficulty",0),0,2);MasterVolume=Mathf.Clamp01(PlayerPrefs.GetFloat("volume",.65f));MusicEnabled=PlayerPrefs.GetInt("music",1)==1;ShakeEnabled=PlayerPrefs.GetInt("shake",1)==1;AutoFire=PlayerPrefs.GetInt("autofire",1)==1;MouseControl=PlayerPrefs.GetInt("mouse",0)==1;}
 public void SaveSettings(){if(qaRunning)return;PlayerPrefs.SetInt("highscore",HighScore);PlayerPrefs.SetInt("unlocked",Unlocked);PlayerPrefs.SetInt("ship",Ship);PlayerPrefs.SetInt("difficulty",Difficulty);PlayerPrefs.SetFloat("volume",MasterVolume);PlayerPrefs.SetInt("music",MusicEnabled?1:0);PlayerPrefs.SetInt("shake",ShakeEnabled?1:0);PlayerPrefs.SetInt("autofire",AutoFire?1:0);PlayerPrefs.SetInt("mouse",MouseControl?1:0);SaveVoiceSettings();PlayerPrefs.Save();}
 void OnApplicationQuit(){SaveSettings();Time.timeScale=1;}
 void ChangeMusic(int stage){if(!music)return;string name=new[]{"MusicSea","MusicCity","MusicOrbit","MusicHangar"}[stage];var next=Clip(name);if(music.clip==next&&(music.isPlaying||AudioSettings.dspTime<musicScheduledUntil))return;music.Stop();music.clip=next;musicBlend=0;double when=AudioSettings.dspTime+.06;musicScheduledUntil=when;if(music.clip)music.PlayScheduled(when);if(musicIntensity){musicIntensity.Stop();musicIntensity.clip=stage<3?Clip(name+"Intensity"):null;if(musicIntensity.clip)musicIntensity.PlayScheduled(when);}}
 public void Sound(string name,float volume=1){var c=Clip(name);if(c&&sfx)sfx.PlayOneShot(c,volume*MasterVolume);}
 public void SetupHangar(){State=FlightState.Hangar;Time.timeScale=1;ClearBattle();if(Player)Destroy(Player);if(hitPoint)Destroy(hitPoint.gameObject);if(focusRing)Destroy(focusRing.gameObject);if(showcase)Destroy(showcase);World.SetStage(0);World.Speed=3;World.Scrolling=true;RefreshShowcase();ChangeMusic(3);Cam.orthographicSize=12.8f;}
 public void SelectShip(int n){int next=(n+3)%3;if(next==Ship)return;Ship=next;SaveSettings();RefreshShowcase();Sound("Click",.5f);}
 public void BeginRun(bool practice=false){ResetFeatures();Endless=false;EndlessLoop=0;Practice=practice;Score=Combo=MaxCombo=Grazes=Kills=campaignDamage=0;CampaignTime=0;DamageBoost=1+researchFire*.04f;upgradeArmor=upgradeFire=upgradeEnergy=0;Energy=35+(PilotLevel(Ship)>=3?10:0);Overdrive=0;Bombs=Difficulty==0?4:3;Hull=MaxHull;Weapon=Ship;WeaponMode=0;Stage=practice?PracticeStage:0;if(showcase)Destroy(showcase);CreatePlayer();BeginStage();SaveSettings();}
 void CreatePlayer(){if(Player)Destroy(Player);if(hitPoint)Destroy(hitPoint.gameObject);if(focusRing)Destroy(focusRing.gameObject);Player=Art.Model(new[]{"Kestrel","Manta","Needle"}[Ship],null);Player.transform.localScale=Vector3.one*.72f;PlayerPos=new Vector3(0,1,-8);Player.transform.position=PlayerPos;AddShipExhaust(Player.transform);
 hitPoint=Art.Primitive(null,"Pilot collision core",PlayerPos+Vector3.up*.6f,Vector3.one*.16f,Art.Mat("hitpoint",Color.white,true),PrimitiveType.Sphere).transform;focusRing=Art.Ring(null,.42f,Art.Cyan,.025f);PrepareFrame();}
 void BeginStage(){ResetStageFeatures();ResetEncounterDirector();ClearBattle();World.SetStage(Stage);World.Speed=Stage==0?8:Stage==1?10:9;World.Scrolling=true;State=FlightState.Briefing;Time.timeScale=1;StageTime=0;waveIndex=0;spawnClock=2;bossSpawned=false;bossPhase=-1;stageDamage=0;stageEndClock=0;stageBanner=6;warningClock=0;briefClock=0;invuln=3;fireClock=missileClock=0;PlayerPos=new Vector3(0,1,-8);Player.transform.position=PlayerPos;ChangeMusic(Stage);RadioName=PilotNames[Ship]+" / 小队通讯";RadioText=new[]{"海面下是最后一支撤离船队。苍隼，我们替他们打开航线。","都市上空的雷暴并非天气。干扰塔正在把居民困在防线内。","天环把所有人类信号判定为威胁。带着我们的声音，飞进它的心脏。"}[Stage];dialogClock=10;}
 public void Launch(){if(State!=FlightState.Briefing)return;State=FlightState.Playing;stageBanner=5;Sound("Overdrive",.35f);}
 public void Pause(){if(State==FlightState.Playing){State=FlightState.Paused;Time.timeScale=0;}else if(State==FlightState.Paused){State=FlightState.Playing;Time.timeScale=1;}SyncVoicePause();Sound("Click");}
 void ClearBattle(){bombFlash=shake=hitStop=0;ClearNova();ClearBossEncounter();ResetArmament();ResetFeedback();foreach(var s in shocks)if(s.line)Destroy(s.line.gameObject);shocks.Clear();foreach(var e in Enemies)if(e.go)Destroy(e.go);Enemies.Clear();Bullets.Clear();foreach(var p in Supplies)if(p.go)Destroy(p.go);Supplies.Clear();foreach(var b in Beams)if(b.go)Destroy(b.go);Beams.Clear();sparks.Clear();Boss=null;}
 void Update(){ApplyViewport();if(!qaRunning&&Input.GetKeyDown(KeyCode.F12)){string folder=Path.Combine(Application.persistentDataPath,"Screenshots");Directory.CreateDirectory(folder);string capture=Path.Combine(folder,"Skybreak-"+DateTime.Now.ToString("yyyyMMdd-HHmmss")+".png");ScreenCapture.CaptureScreenshot(capture);Debug.Log("SKYBREAK_SCREENSHOT "+capture);}float udt=Time.unscaledDeltaTime;smoothedFps=Mathf.Lerp(smoothedFps,1/Mathf.Max(.001f,udt),.03f);UpdateVoices(udt);MixSoundtrack(udt);if(!qaRunning&&Input.GetKeyDown(KeyCode.F11))Screen.fullScreen=!Screen.fullScreen;
 if(State==FlightState.Hangar){if(showcase)showcase.transform.rotation=Quaternion.Euler(6+Mathf.Sin(Time.time*.4f)*3,-24+Mathf.Sin(Time.time*.22f)*9,-10);if(!qaRunning&&Input.GetKeyDown(KeyCode.Return)&&menuPage==0)BeginRun();if(!qaRunning&&Input.GetKeyDown(KeyCode.LeftArrow)&&menuPage==0)SelectShip(Ship-1);if(!qaRunning&&Input.GetKeyDown(KeyCode.RightArrow)&&menuPage==0)SelectShip(Ship+1);return;}
 if(State==FlightState.Briefing){briefClock+=udt;if(!qaRunning&&(Input.GetKeyDown(KeyCode.Return)||Input.GetKeyDown(KeyCode.Space)))Launch();UpdateCamera(udt);return;}
 if(!qaRunning&&Input.GetKeyDown(KeyCode.Escape)){if(State==FlightState.Playing||State==FlightState.Paused)Pause();}
 if(State!=FlightState.Playing){if(hitPoint)hitPoint.gameObject.SetActive(false);if(focusRing)focusRing.gameObject.SetActive(false);return;}
 float dt=Mathf.Min(Time.deltaTime,.05f);if(hitStop>0){hitStop-=dt;dt*=.18f;}if(!qaRunning&&(Input.GetKeyDown(KeyCode.Q)||Input.GetKeyDown(KeyCode.JoystickButton5)))UsePilotSkill();if(!qaRunning&&(Input.GetKeyDown(KeyCode.Space)||Input.GetKeyDown(KeyCode.JoystickButton1)))UseBomb();if(!qaRunning&&(Input.GetKeyDown(KeyCode.E)||Input.GetKeyDown(KeyCode.JoystickButton2)))UseOverdrive();if(!qaRunning&&(Input.GetKeyDown(KeyCode.R)||Input.GetKeyDown(KeyCode.JoystickButton3))){SwitchWeaponMode();}
 bool focused=Input.GetKey(KeyCode.LeftShift)||Input.GetKey(KeyCode.RightShift)||Input.GetKey(KeyCode.JoystickButton4);Vector2 movement=new Vector2(Input.GetAxisRaw("Horizontal"),Input.GetAxisRaw("Vertical"));movement=Vector2.ClampMagnitude(movement,1);
 if(MouseControl&&!qaRunning){Ray ray=Cam.ScreenPointToRay(Input.mousePosition);Plane p=new Plane(Vector3.up,new Vector3(0,1,0));if(p.Raycast(ray,out var distance)){Vector3 target=ray.GetPoint(distance);Vector3 v=target-PlayerPos;movement=Vector2.ClampMagnitude(new Vector2(v.x,v.z)*2,1);}}
 if(qaRunning){movement=Vector2.zero;focused=false;}Fly(movement,focused,dt);Tick(dt,focused,AutoFire||Input.GetKey(KeyCode.Z)||Input.GetMouseButton(0)||Input.GetKey(KeyCode.JoystickButton0));UpdateCamera(dt);}
 public void Fly(Vector2 move,bool focus,float dt){float speed=(Ship==2?13.5f:Ship==1?10:12)*(focus?.42f:1);PlayerPos+=new Vector3(move.x,0,move.y)*speed*dt;PlayerPos.x=Mathf.Clamp(PlayerPos.x,-10,10);PlayerPos.z=Mathf.Clamp(PlayerPos.z,-10,10);Player.transform.position=PlayerPos;Player.transform.rotation=Quaternion.Slerp(Player.transform.rotation,Quaternion.Euler(-move.y*7-weaponKick*3,move.x*-5,-move.x*24),1-Mathf.Exp(-dt*12));moveLast=move;
 hitPoint.gameObject.SetActive(focus);hitPoint.position=PlayerPos+Vector3.up*.5f;focusRing.gameObject.SetActive(focus);focusRing.transform.position=PlayerPos+Vector3.up*.08f;}
 public void Tick(float dt,bool focused,bool firing){TickFeatures(dt);TickEncounterDirector(dt);TickFeedback(dt);AnimateFrame(dt);StageTime+=dt;CampaignTime+=dt;invuln=Mathf.Max(0,invuln-dt);Overdrive=Mathf.Max(0,Overdrive-dt);comboClock-=dt;if(comboClock<=0)Combo=0;warningClock=Mathf.Max(0,warningClock-dt);dialogClock=Mathf.Max(0,dialogClock-dt);stageBanner=Mathf.Max(0,stageBanner-dt);bombFlash=Mathf.Max(0,bombFlash-dt*1.7f);shake=Mathf.Max(0,shake-dt*1.7f);
 if(invuln>0){Player.transform.localScale=Vector3.one*(Mathf.Sin(Time.time*36)>0?.72f:.65f);}else Player.transform.localScale=Vector3.one*.72f;
 TickArmament(dt,focused,firing&&stageEndClock==0);
 UpdateEnemies(dt);UpdateBullets(dt);UpdateSupplies(dt);UpdateBeams(dt);UpdateSparks(dt);if(State!=FlightState.Playing)return;
 if(stageEndClock>0){stageEndClock-=dt;if(stageEndClock<=0)CompleteStage();return;}
 if(StageTime<115){spawnClock-=dt;if(spawnClock<=0){SpawnWave(waveIndex++);spawnClock=Difficulty==0?4.1f:3.4f;}}
 else if(!bossSpawned){bossSpawned=true;warningClock=4;Sound("Warning");RadioName="威胁识别";RadioText=BossNames[Stage]+"已进入航线。注意核心暴露与激光预警。";dialogClock=6;}
 if(bossSpawned&&Boss==null&&warningClock<=0&&StageTime<121)SpawnBoss();
 if(StageTime>42&&StageTime<42+dt){pilotSpeaker=(Ship+1)%3;RadioName=PilotNames[pilotSpeaker]+" / 小队通讯";RadioText=new[]{"补给运输机正在穿越防线。击落它，回收武装和修复模块。","小心道路上方的瞄准线。先离开标记，再反击。","擦过弹幕可以储存超载能量。核心即将暴露。"}[Stage];dialogClock=6;}
 }
 public void AddBullet(Vector3 p,Vector3 velocity,bool friendly,int style,float damage=1,float radius=.17f,bool homing=false,float curve=0,int pierce=0,int kind=0){if(Bullets.Count>=3400)return;if(!friendly)enemyRoundsSpawned++;Bullets.Add(new Round{pos=p,prev=p,velocity=velocity,friendly=friendly,style=style,damage=damage,radius=radius,life=friendly?(kind==3?1.0f:2.6f):10,homing=homing,curve=curve,pierce=pierce,kind=kind});}
 public void SpawnWave(int wave){SpawnChapterWave(wave);}
 public Hostile SpawnEnemy(int kind,Vector3 pos,int pattern){var go=Art.Model(kind==0?"Drone":kind==1?"Interceptor":kind==2?"Gunship":"Leviathan",null);go.transform.position=pos;float scale=kind==0?.8f:kind==1?.7f:kind==2?.95f:.45f;go.transform.localScale=Vector3.one*scale;go.transform.rotation=Quaternion.Euler(0,180,0);float hp=(kind==0?12:kind==1?26:kind==2?80:125)*(1+Stage*.16f);var e=new Hostile{go=go,pos=pos,origin=pos,kind=kind,pattern=pattern,hp=hp*(1+EndlessLoop*.3f),maxHp=hp*(1+EndlessLoop*.3f),fire=1.5f+UnityEngine.Random.value,phase=UnityEngine.Random.value*6,renderers=go.GetComponentsInChildren<Renderer>()};e.baseColors=RendererColors(e.renderers);Enemies.Add(e);return e;}
 public void SpawnBoss(){Boss=SpawnEnemy(3,new Vector3(0,1,21),0);Destroy(Boss.go);Boss.go=Art.Model(new[]{"Leviathan","Tempest","Seraph"}[Stage],null);Boss.go.transform.position=Boss.pos;Boss.go.transform.rotation=Quaternion.Euler(0,180,0);Boss.go.transform.localScale=Vector3.one*1.15f;Boss.renderers=Boss.go.GetComponentsInChildren<Renderer>();Boss.baseColors=RendererColors(Boss.renderers);Boss.boss=true;Boss.hp=Boss.maxHp=(Stage==0?2600:Stage==1?3400:4300)*(Difficulty==0?.8f:1)*(1+EndlessLoop*.35f);Boss.fire=1;Boss.age=0;bossPhase=-1;warningClock=0;InitBossEncounter();}
 void UpdateEnemies(float dt){for(int i=Enemies.Count-1;i>=0;i--){var e=Enemies[i];if(!e.go)continue;e.age+=dt;e.fire-=dt;e.flash=Mathf.Max(0,e.flash-dt);e.recoil=Mathf.MoveTowards(e.recoil,0,dt*1.7f);if(e.owner!=null){TickBossModule(e,dt);continue;}if(e.boss){e.pos.z=Mathf.MoveTowards(e.pos.z,8.2f,dt*3);e.pos.x=Mathf.Sin(e.age*.35f)*5.7f;int phase=e.hp/e.maxHp>.67f?0:e.hp/e.maxHp>.33f?1:2;if(phase!=bossPhase){bossPhase=phase;Burst(e.pos,24,2);if(phase>0){Sound("Warning",.7f);warningClock=1.5f;CancelBullets(false);}}TickBossEncounter(e,phase,dt);}
 else {float speed=e.elite?(e.age<3?3.8f:e.age<19?.25f:4.5f):e.kind>=2?2.1f:e.kind==1?4.6f:5.6f;e.pos.z-=dt*speed;e.pos.x=e.origin.x+Mathf.Sin(e.age*(e.pattern==5?2:1.4f)+e.phase)*(e.pattern==0?.4f:e.pattern==6?2.8f:e.pattern==4?2.2f:1.1f);UpdateWeaponTell(e);if(e.fire<=0&&e.pos.z<13&&e.pos.z>PlayerPos.z+1){EnemyAttack(e);FinishWeaponTell(e);e.fire=e.kind>=2?1.3f:2.2f;}if(e.pos.z<-15){Destroy(e.go);Enemies.RemoveAt(i);continue;}}
 RenderEnemyFeedback(e);
 if(invuln<=0&&(e.pos-PlayerPos).sqrMagnitude<(e.boss?5.5f:e.kind>=2?1.3f:.65f))HitPlayer();
 }}
 void EnemyAttack(Hostile e){if(e.elite){for(int j=0;j<16;j++){float a=e.age*.4f+j*Mathf.PI*2/16;AddBullet(e.pos,new Vector3(Mathf.Sin(a),0,Mathf.Cos(a))*4.5f*DifficultySpeed,false,2);}}Vector3 aim=((e.aimReady?e.lockedAim:PlayerPos)-e.pos).normalized;aim.y=0;float speed=(e.kind>=2?7:6)*DifficultySpeed;int n=e.kind==0?1:e.kind==1?3:5;for(int k=0;k<n;k++){float a=(k-(n-1)*.5f)*11;AddBullet(e.pos+Vector3.back*.5f,Quaternion.Euler(0,a,0)*aim*speed,false,1);}}
 void BossAttack(Hostile e,int phase){if(Stage>0){AdvancedBossAttack(e,phase);return;}int attack=(int)(e.age/6)%3;float speed=(4.7f+phase*.65f+Stage*.3f)*DifficultySpeed;
 if(attack==0){int n=16+Stage*4+phase*4;float start=e.age*.58f;for(int j=0;j<n;j++){float a=start+j*Mathf.PI*2/n;AddBullet(e.pos+new Vector3(0,0,-1),new Vector3(Mathf.Sin(a),0,Mathf.Cos(a))*speed,false,phase==2?2:1,1,.18f);}}
 else if(attack==1){for(int s=-1;s<=1;s+=2){Vector3 p=e.pos+new Vector3(s*2.7f,0,-1);Vector3 aim=(PlayerPos-p).normalized;for(int j=-2-phase;j<=2+phase;j++)AddBullet(p,Quaternion.Euler(0,j*10,0)*aim*(speed+1.5f),false,1,1,.17f);}}
 else {for(int j=-5;j<=5;j++){float a=j*.12f+Mathf.Sin(e.age)*.24f;AddBullet(e.pos+Vector3.back,new Vector3(Mathf.Sin(a),0,-Mathf.Cos(a))*speed,false,2,1,.19f);}if(phase>0&&Beams.Count==0){AddBeam(PlayerPos.x);if(Stage==2){AddBeam(PlayerPos.x-5);AddBeam(PlayerPos.x+5);}}}
 }
 public static float SegmentDistance(Vector3 point,Vector3 a,Vector3 b){Vector3 ab=b-a;float t=Mathf.Clamp01(Vector3.Dot(point-a,ab)/Mathf.Max(.000001f,ab.sqrMagnitude));return Vector3.Distance(point,a+ab*t);}
 void UpdateBullets(float dt){pendingDamage.Clear();bool hurt=false;for(int i=Bullets.Count-1;i>=0;i--){Round b=Bullets[i];b.prev=b.pos;b.age+=dt;if(b.curve!=0)b.velocity=Quaternion.Euler(0,b.curve*dt,0)*b.velocity;if(b.homing&&b.age>(b.kind==4?.16f:.025f)&&Enemies.Count>0){Hostile target=null;float d=float.MaxValue;foreach(var e in Enemies){float dd=(e.pos-b.pos).sqrMagnitude;if(hunters>0&&e.kind>=2)dd*=.55f;if(dd<d){d=dd;target=e;}}if(target!=null){Vector3 desired=(target.pos-b.pos).normalized*24;b.velocity=Vector3.Lerp(b.velocity,desired,dt*5);}}
 b.pos+=b.velocity*dt*(!b.friendly&&Ship==2&&SkillTime>0?.32f:1);b.life-=dt;bool dead=b.life<=0||Mathf.Abs(b.pos.x)>28||b.pos.z<-18||b.pos.z>27;
 if(!dead&&b.friendly){for(int j=Enemies.Count-1;j>=0;j--){var e=Enemies[j];float radius=e.boss?2.65f:e.kind==3?1.8f:e.kind==2?1.35f:e.kind==1?.75f:.67f;if(e!=b.lastHit&&SegmentDistance(e.pos,b.prev,b.pos)<radius+b.radius){if(pendingDamage.ContainsKey(e))pendingDamage[e]+=b.damage;else pendingDamage[e]=b.damage;WeaponImpact(b,e);if(b.pierce>0){b.pierce--;b.lastHit=e;}else dead=true;break;}}}
 else if(!dead&&!b.friendly){float d=SegmentDistance(PlayerPos,b.prev,b.pos);if(d<.18f+b.radius){dead=true;if(invuln<=0)hurt=true;}else if(d<.9f&&!b.grazed){b.grazed=true;Grazes++;Score+=25;Energy=Mathf.Min(100,Energy+1.8f+upgradeEnergy*.6f);Burst(PlayerPos,2,0,.18f);}}
 if(dead)Bullets.RemoveAt(i);else Bullets[i]=b;}foreach(var pair in pendingDamage)if(Enemies.Contains(pair.Key))DamageEnemy(pair.Key,pair.Value);if(hurt)HitPlayer();}
 public void DamageEnemy(Hostile e,float damage){if(!Enemies.Contains(e))return;damage*=BossDamageScale(e);e.hp-=damage;OnArmorImpact(e,damage);if(e.hp>0)return;BossModuleDestroyed(e);Kills++;int points=e.boss?20000:e.kind==3?1000:e.kind==2?650:e.kind==1?250:120;RewardElite(e);Combo++;MaxCombo=Mathf.Max(Combo,MaxCombo);comboClock=4;Score+=points*Mathf.Min(10,1+Combo/8);Energy=Mathf.Min(100,Energy+(e.boss?30:2+upgradeEnergy));OnTargetDestroyed(e,points);
 if(e.boss){foreach(var node in Enemies.ToArray())if(node.owner==e){Destroy(node.go);Enemies.Remove(node);}ClearBossEncounter();Score+=Mathf.Max(0,MaxHull-stageDamage)*1000;stageEndClock=4.2f;CancelBullets(true);Bombs=Mathf.Min(5,Bombs+1);Hull=Mathf.Min(MaxHull,Hull+1);pilotSpeaker=(Ship+1)%3;RadioName=PilotNames[pilotSpeaker]+" / 小队通讯";RadioText=new[]{"要塞沉默了。撤离船队已通过防线，我们前往城市。","雷暴正在消散。最后一个指令源在轨道上——准备爬升。","收到人类识别码。天环停止攻击……我们把天空还给了所有人。"}[Stage];dialogClock=8;Boss=null;}
 else if(e.kind==3||Kills%11==0)SpawnSupply(e.pos,e.kind==3?0:Kills%22==0?1:2);
 Enemies.Remove(e);Destroy(e.go);
 }
 public void HitPlayer(){if(invuln>0||State!=FlightState.Playing)return;Hull--;stageDamage++;campaignDamage++;Combo=0;invuln=2.5f;shake=.8f;hurtEdge=.8f;audioDuck=.4f;Sound("Hit",.9f);Burst(PlayerPos,36,1,.8f);for(int i=Bullets.Count-1;i>=0;i--)if(!Bullets[i].friendly&&(Bullets[i].pos-PlayerPos).sqrMagnitude<5)Bullets.RemoveAt(i);if(Hull>0)PlayPilotBark(Hull<=2?"danger":"hurt",Ship,Hull<=2?100:20);if(Hull<=0){State=FlightState.Defeat;World.Scrolling=false;Post.Flash=0;FinishScore();Sound("Bomb");}}
 public void UseBomb(){if(State!=FlightState.Playing||Bombs<=0||stageEndClock>0||NovaActive)return;Bombs--;invuln=2.5f;bombFlash=.055f;PlayPilotBark("bomb",Ship,75);BeginNova();CancelBullets(true);}
 public void UseOverdrive(){if(State!=FlightState.Playing||Energy<100||Overdrive>0||stageEndClock>0)return;Energy=0;Overdrive=8+upgradeEnergy;invuln=1;CancelBullets(true);Sound("Overdrive");PlayPilotBark("overdrive",Ship,80);cutinClock=1.65f;cutinIsOverdrive=true;Toast("天翼机甲展开 · OVERDRIVE",3);Shockwave(PlayerPos,Art.Cyan,10);bombFlash=.2f;shake=.3f;}
 void CancelBullets(bool reward){for(int i=Bullets.Count-1;i>=0;i--){if(Bullets[i].friendly)continue;if(reward)Score+=10;if(i%4==0)Burst(Bullets[i].pos,1,0,.25f);Bullets.RemoveAt(i);}}
 public void SpawnSupply(Vector3 p,int kind){var go=new GameObject("Supply");var color=kind==0?new Color(.15f,1,.5f):kind==1?Art.Orange:Art.Cyan;var core=Art.Primitive(go.transform,"Module",Vector3.zero,Vector3.one*.55f,Art.Mat("supply"+kind,color,true),PrimitiveType.Cube);core.transform.rotation=Quaternion.Euler(25,45,25);Art.Ring(go.transform,.65f,color,.055f);Supplies.Add(new Supply{go=go,pos=p,kind=kind});}
 void UpdateSupplies(float dt){for(int i=Supplies.Count-1;i>=0;i--){var p=Supplies[i];p.age+=dt;Vector3 to=PlayerPos-p.pos;p.pos+=to.sqrMagnitude<16?to.normalized*dt*9:Vector3.back*dt*3;p.go.transform.position=p.pos;p.go.transform.rotation=Quaternion.Euler(0,p.age*75,0);if(to.sqrMagnitude<1.1f){if(p.kind==0)Hull=Mathf.Min(MaxHull,Hull+1);else if(p.kind==1)Bombs=Mathf.Min(5,Bombs+1);else Energy=Mathf.Min(100,Energy+25);Score+=500;Sound("Pickup");Burst(p.pos,18,0);Destroy(p.go);Supplies.RemoveAt(i);}else if(p.pos.z<-15){Destroy(p.go);Supplies.RemoveAt(i);}}}
 public void AddBeam(float x){if(Mathf.Abs(x)>11)return;var o=new GameObject("Telegraphed beam");var l=Art.Line(o.transform,"Laser",new[]{new Vector3(x,1,-13),new Vector3(x,1,17)},Art.Orange,.06f);Beams.Add(new Beam{x=x,go=o,line=l,duration=3.1f});}
 void UpdateBeams(float dt){for(int i=Beams.Count-1;i>=0;i--){var b=Beams[i];b.age+=dt;if(b.age>1.75f){if(!b.fired){b.fired=true;Sound("Overdrive",.35f);}b.line.startWidth=b.line.endWidth=.62f;if(Mathf.Abs(PlayerPos.x-b.x)<.4f&&invuln<=0)HitPlayer();}else b.line.startWidth=b.line.endWidth=.04f+Mathf.Sin(b.age*25)*.016f;if(b.age>b.duration){Destroy(b.go);Beams.RemoveAt(i);}}}
 public void Burst(Vector3 p,int count,int style,float size=1){for(int i=0;i<count&&sparks.Count<1500;i++){float life=UnityEngine.Random.Range(.2f,.85f)*(style==1?1.4f:1);sparks.Add(new Spark{pos=p,velocity=UnityEngine.Random.insideUnitSphere*UnityEngine.Random.Range(1,7)*size,life=life,max=life,size=UnityEngine.Random.Range(.06f,.25f)*size,style=style==1?(i%4==0?4:i%3==0?5:3):style==2?2:style==3?3:0});}}
 void UpdateSparks(float dt){for(int i=sparks.Count-1;i>=0;i--){var s=sparks[i];s.life-=dt;if(s.life<=0){sparks.RemoveAt(i);continue;}s.pos+=s.velocity*dt;s.velocity*=1-dt*1.7f;sparks[i]=s;}}
 void LateUpdate(){if(shotMats==null||State==FlightState.Hangar)return;enemyRims.Clear();foreach(var list in draws)list.Clear();foreach(var b in Bullets){if(b.friendly&&b.kind>0){DrawWeaponRound(b);continue;}Vector3 scale=b.friendly?new Vector3(b.radius*1.3f,b.radius*1.3f,b.homing?.65f:1.15f):Vector3.one*b.radius*2;Quaternion rot=Quaternion.LookRotation(b.velocity.sqrMagnitude>.01f?b.velocity:Vector3.forward);draws[b.style].Add(Matrix4x4.TRS(b.pos,rot,scale));if(!b.friendly){enemyRims.Add(Matrix4x4.TRS(b.pos,Quaternion.identity,Vector3.one*b.radius*2.65f));draws[3].Add(Matrix4x4.TRS(b.pos+Vector3.up*.03f,Quaternion.identity,Vector3.one*b.radius*.95f));}}
 foreach(var s in sparks){float k=s.life/s.max;float size=s.size*(s.style==4?1+(1-k)*3:k);Quaternion rotation=s.style==4?Cam.transform.rotation:s.style==3&&s.velocity.sqrMagnitude>.01f?Quaternion.LookRotation(s.velocity):Quaternion.Euler(s.life*200,s.life*120,0);Vector3 stretch=s.style==3?new Vector3(.42f,.42f,2.8f):Vector3.one;draws[s.style].Add(Matrix4x4.TRS(s.pos,rotation,stretch*size*(s.style==4?3:1)));}
 for(int offset=0;offset<enemyRims.Count;offset+=1023){int n=Mathf.Min(1023,enemyRims.Count-offset);enemyRims.CopyTo(offset,matrices,0,n);Graphics.DrawMeshInstanced(sphere,0,projectileRim,matrices,n,null,ShadowCastingMode.Off,false,0,Cam);}
 for(int i=0;i<draws.Length;i++){var list=draws[i];for(int offset=0;offset<list.Count;offset+=1023){int n=Mathf.Min(1023,list.Count-offset);list.CopyTo(offset,matrices,0,n);Graphics.DrawMeshInstanced(i==4?quad:i==5?cube:sphere,0,shotMats[i],matrices,n,null,ShadowCastingMode.Off,false,0,Cam);}}}

 void ApplyViewport(){if(!Cam)return;float aspect=Screen.width/(float)Mathf.Max(1,Screen.height);const float desired=16f/9;if(aspect>desired){float w=desired/aspect;Cam.rect=new Rect((1-w)/2,0,w,1);}else{float h=aspect/desired;Cam.rect=new Rect(0,(1-h)/2,1,h);}}
 void UpdateCamera(float dt){Cam.orthographicSize=Mathf.Lerp(Cam.orthographicSize,12.8f,dt*3);var target=cameraBase+new Vector3(PlayerPos.x*.06f,0,0);if(ShakeEnabled)target+=UnityEngine.Random.insideUnitSphere*shake*.35f;Cam.transform.position=target;Post.Flash=bombFlash;Post.Damage=hurtEdge;Post.Intensity=Overdrive>0?1:.6f;}
 public void BeginEndless(){BeginRun();Endless=true;}
 void CompleteStage(){if((Stage>=2||Practice)&&!Endless){State=FlightState.Victory;World.Scrolling=false;ChangeMusic(3);FinishScore();return;}if(!Endless)Unlocked=Mathf.Max(Unlocked,Stage+1);else if(Stage==2)EndlessLoop++;RollUpgrades();SaveSettings();State=FlightState.Upgrade;World.Scrolling=false;UpgradePick=-1;}
 public void ApplyUpgrade(int n){if(State!=FlightState.Upgrade)return;UpgradePick=n;ApplyFeatureUpgrade(n);Stage=Endless?(Stage+1)%3:Stage+1;BeginStage();Sound("Pickup");}
 void FinishScore(){RewardPilot();HighScore=Mathf.Max(HighScore,Score);if(State==FlightState.Victory&&!Practice)Unlocked=2;SaveSettings();}
}
}
