using UnityEngine;
using System;
using System.Collections;
using System.IO;
using System.Collections.Generic;
namespace Skybreak {
public partial class SkyGame {
 IEnumerator VerifyRuntime(){qaRunning=true;Application.runInBackground=true;QualitySettings.vSyncCount=0;Application.targetFrameRate=60;string output=Path.Combine(Directory.GetCurrentDirectory(),"QA");foreach(string arg in Environment.GetCommandLineArgs())if(arg.StartsWith("--sky-output="))output=arg.Substring(13);Directory.CreateDirectory(output);var results=new List<string>();int oldShip=Ship;int oldHigh=HighScore,oldUnlocked=Unlocked;bool oldAuto=AutoFire;int oldDifficulty=Difficulty;
 Action<bool,string> check=(condition,name)=>{results.Add((condition?"PASS ":"FAIL ")+name);Debug.Log(results[results.Count-1]);};
 for(int m=0;m<3;m++){string name=new[]{"MusicSea","MusicCity","MusicOrbit"}[m];check(Clip(name)&&Clip(name+"Intensity")&&Clip(name).samples==Clip(name+"Intensity").samples,"Music "+m+" intensity stem is sample aligned");}
 SelectShip(0);yield return new WaitForSeconds(2);
 var hangarTrack=music.clip;int sampleBefore=music.timeSamples;var sameWorld=World;for(int i=0;i<6;i++){SelectShip(i%3);yield return new WaitForSeconds(.12f);}check(music.clip==hangarTrack&&music.timeSamples>sampleBefore&&music.isPlaying,"Six ship changes preserve music clip and advance playhead");check(World==sameWorld,"Ship selection keeps existing world instead of rebuilding hangar");SelectShip(0);
ScreenCapture.CaptureScreenshot(Path.Combine(output,"01-hangar.png"));yield return new WaitForSeconds(.5f);BeginRun();check(State==FlightState.Briefing,"Campaign begins at mission briefing");Launch();check(State==FlightState.Playing,"Briefing launches gameplay");AutoFire=true;
 yield return new WaitForSeconds(3);int beforeKills=Kills;SpawnEnemy(0,new Vector3(0,1,-2),0);for(int j=0;j<200&&Kills==beforeKills;j++)yield return null;check(Kills>beforeKills,"Live automatic shots destroy an enemy");ScreenCapture.CaptureScreenshot(Path.Combine(output,"02-coast.png"));yield return new WaitForSeconds(.25f);
 int oldHull=Hull;invuln=0;Bullets.Clear();AddBullet(PlayerPos+Vector3.forward,Vector3.back*20,false,1);yield return new WaitForSeconds(.15f);check(Hull==oldHull-1,"Hostile projectile damages player once");int protectedHull=Hull;AddBullet(PlayerPos+Vector3.forward,Vector3.back*20,false,1);yield return new WaitForSeconds(.15f);check(Hull==protectedHull,"Invulnerability prevents consecutive damage");
 int gr=Grazes;Bullets.Clear();AddBullet(PlayerPos+new Vector3(.65f,0,1),Vector3.back*12,false,1);yield return new WaitForSeconds(.3f);check(Grazes>gr,"Near miss awards graze energy");int afterGraze=Grazes;yield return new WaitForSeconds(.3f);check(Grazes==afterGraze,"A projectile can award graze only once");
 float clock=StageTime;Pause();yield return new WaitForSecondsRealtime(.4f);check(State==FlightState.Paused&&Mathf.Abs(StageTime-clock)<.001f,"Pause freezes simulation time");Pause();check(State==FlightState.Playing,"Pause resumes");
 int oldBomb=Bombs;AddBullet(PlayerPos+Vector3.forward*5,Vector3.back,false,1);UseBomb();check(Bombs==oldBomb-1&&Bullets.TrueForAll(b=>b.friendly),"Bomb consumes stock and clears hostile bullets");Energy=100;UseOverdrive();check(Overdrive>7&&Energy==0,"Full reactor activates overdrive");yield return new WaitForSeconds(.4f);check(frameForm&&frameForm.activeSelf&&airForm&&!airForm.activeSelf,"Overdrive transforms aircraft into animated mecha");check(musicBlend>.4f&&musicIntensity.isPlaying,"Overdrive raises synchronized music intensity");RestoreSoundtrack(true);yield return new WaitForSeconds(.25f);check(music.isPlaying&&musicIntensity.isPlaying&&Mathf.Abs(music.timeSamples-musicIntensity.timeSamples)<2048,"Music stems resynchronize after audio reset callback");ScreenCapture.CaptureScreenshot(Path.Combine(output,"07-mecha-overdrive.png"));int h=Hull;SpawnSupply(PlayerPos,0);yield return new WaitForSeconds(.15f);check(Hull==Mathf.Min(MaxHull,h+1),"Repair pickup heals armor");

 for(int pilot=0;pilot<3;pilot++){Ship=pilot;BeginRun();Launch();AutoFire=false;invuln=999;var target=SpawnEnemy(3,new Vector3(0,1,3),0);float hp=target.hp;UsePilotSkill();check(SkillCooldown>0&&SkillTime>0,"Pilot "+pilot+" activates unique skill");float cooldown=SkillCooldown;UsePilotSkill();check(Mathf.Abs(cooldown-SkillCooldown)<.01f,"Pilot skill respects cooldown");if(pilot==0)check(Bullets.FindAll(b=>b.friendly&&b.homing).Count>=18,"Aoi fires homing swarm");if(pilot==1)check(target.hp<hp,"Rin salvo damages hostile");if(pilot==2){Bullets.Clear();AddBullet(new Vector3(8,1,8),Vector3.back*10,false,1);yield return new WaitForSeconds(.5f);check(Bullets.Count>0&&Bullets[0].pos.z>5.8f,"Yuki field slows hostile projectiles");}yield return new WaitForSeconds(.45f);ScreenCapture.CaptureScreenshot(Path.Combine(output,"06-pilot-skill-"+pilot+".png"));yield return new WaitForSeconds(.2f);}
 Ship=0;BeginRun();Launch();AutoFire=false;StageTime=52.1f;yield return new WaitForSeconds(.15f);check(eliteTarget!=null&&eliteTarget.elite,"Midstage elite objective spawns");if(eliteTarget!=null)DamageEnemy(eliteTarget,10000);check(sideObjectiveComplete,"Elite defeat completes optional objective");ClearBattle();stageBanner=dialogClock=toastClock=0;var armored=SpawnEnemy(2,new Vector3(0,1,2),0);float armorHp=armored.hp;DamageEnemy(armored,5);RenderEnemyFeedback(armored);check(armored.hp<armorHp&&armored.flash>0&&armored.recoil>0&&impactAudio.isPlaying,"Nonlethal hit produces armor flash, recoil and impact audio");ScreenCapture.CaptureScreenshot(Path.Combine(output,"10-armor-impact.png"));yield return new WaitForSeconds(.04f);DamageEnemy(armored,10000);check(deathClouds.Count>0&&scorePops.Count>0&&hitStop>0,"Heavy kill produces delayed explosions, score feedback and hit stop");yield return new WaitForSeconds(.16f);ScreenCapture.CaptureScreenshot(Path.Combine(output,"09-impact-feedback.png"));yield return new WaitForSeconds(.15f);ClearBattle();UpgradeOptions=new[]{3,4,5};ApplyFeatureUpgrade(0);Shoot(false);check(Bullets.Exists(b=>b.friendly&&Mathf.Abs(b.pos.x-PlayerPos.x)>1.3f),"Wingman augment adds live side fire");ApplyFeatureUpgrade(1);ApplyFeatureUpgrade(2);check(hunters==1&&focusLevel==1,"Distinct upgrade choices coexist");
 ClearBattle();Ship=2;Weapon=2;WeaponMode=0;PlayerPos=new Vector3(0,1,-8);SpawnEnemy(0,new Vector3(0,1,-1),0);SpawnEnemy(0,new Vector3(0,1,2),0);int piercedKills=Kills;Shoot(true);yield return new WaitForSeconds(.5f);check(Kills>=piercedKills+2,"Ion lance pierces multiple live enemies");
 yield return VerifyArsenal(check,output);yield return VerifySetpieces(check,output);Ship=0;VerifyEncounterRules(check);BeginEndless();Launch();Stage=2;CompleteStage();check(State==FlightState.Upgrade&&EndlessLoop==1,"Endless finale advances escalation");ApplyUpgrade(0);check(State==FlightState.Briefing&&Stage==0&&Endless,"Endless mode wraps into next circuit");BeginRun();Launch();AutoFire=true;invuln=999;
 for(int stage=0;stage<3;stage++){Stage=stage;BeginStage();Launch();StageTime=116;bossSpawned=true;SpawnBoss();Boss.pos=new Vector3(0,1,8.2f);Boss.origin=Boss.pos;Boss.go.transform.position=Boss.pos;Boss.age=12;invuln=999;stageBanner=0;dialogClock=0;long emitted=enemyRoundsSpawned;yield return new WaitForSeconds(6);check(Boss!=null&&enemyRoundsSpawned>emitted,"Stage "+(stage+1)+" boss emits live bullet patterns");ScreenCapture.CaptureScreenshot(Path.Combine(output,"03-boss-"+stage+".png"));yield return new WaitForSeconds(.3f);if(Boss!=null){Boss.hp=Boss.maxHp*.6f;yield return new WaitForSeconds(.4f);check(bossPhase==1,"Boss phase 2 activates");Boss.hp=Boss.maxHp*.3f;yield return new WaitForSeconds(.4f);check(bossPhase==2,"Boss phase 3 activates");DamageEnemy(Boss,100000);}yield return new WaitForSeconds(4.6f);if(stage<2){check(State==FlightState.Upgrade,"Stage clear offers upgrade");ScreenCapture.CaptureScreenshot(Path.Combine(output,"04-upgrade.png"));yield return new WaitForSeconds(.3f);int next=Stage+1;ApplyUpgrade(stage);check(State==FlightState.Briefing&&Stage==next,"Upgrade advances to next mission");}else check(State==FlightState.Victory,"Final boss leads to ending and score");}
 ScreenCapture.CaptureScreenshot(Path.Combine(output,"05-victory.png"));yield return new WaitForSeconds(.5f);BeginRun();Launch();Hull=1;invuln=0;HitPlayer();check(State==FlightState.Defeat,"Zero armor opens defeat screen");BeginRun();check(Hull==MaxHull&&State==FlightState.Briefing,"Retry resets hull and mission state");SetupHangar();check(State==FlightState.Hangar&&Enemies.Count==0&&Bullets.Count==0,"Returning to hangar clears combat entities");
 Ship=oldShip;HighScore=oldHigh;Unlocked=oldUnlocked;AutoFire=oldAuto;Difficulty=oldDifficulty;SaveSettings();results.Add("Observed frame rate: "+Mathf.RoundToInt(smoothedFps));WriteVerificationIdentity(output,"runtime");File.WriteAllLines(Path.Combine(output,"runtime-results.txt"),results);Debug.Log("SKYBREAK_RUNTIME_QA_COMPLETE");Application.Quit(results.Exists(s=>s.StartsWith("FAIL"))?2:0);
 }
}
}
